# .goreleaser.yaml
# GoReleaser configuration for occo
# https://goreleaser.com/introduction

version: 2

project_name: occo

before:
  hooks:
    - go mod tidy

builds:
  - id: occo
    binary: occo
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/qbicsoftware/occo/internal/version.Version={{.Version}}

changelog:
  disable: true

release:
  github:
    owner: qbicsoftware
    name: occo
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

checksum:
  name_template: "{{.ProjectName}}-{{.Version}}-checksums.txt"
  algorithm: sha256

announce:
  twitter:
    enabled: false
